name: Build Armbian Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "uefi-x86"
          armbian_release: "jammy"
          armbian_target: "build"
          armbian_ui: "server"
          armbian_runner_clean: "yes"
