name: Build Armbian

on:
  workflow_dispatch:

jobs:
  build-armbian:
    runs-on: ubuntu-latest-arm # ubuntu-22.04 # ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl gnupg2 sudo

      - name: Run Armbian Build
        uses: armbian/build@prepre
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"
          armbian_release:   "noble"
          armbian_target:    "build"
          armbian_board:     "bananapim5"

